Output create-no-disk.gif

Set Width 1200
Set Height 600
Set Theme "Dracula"
Set TypingSpeed 0.1
Set FontFamily "JetBrains Mono"
Set WindowBar Colorful
Set MarginSize 20
Set MarginFill "#bd93f9"


Set CornerRadius 10
Set Padding 20


Type "qemantra create"

Sleep 350ms

Enter

Type "manjaro"

Sleep 350ms

Enter

Sleep 350ms

Type "5"

Sleep 350ms

Enter

Sleep 350ms 

Type "4G"


Sleep 350ms 
Enter


Sleep 1s 
Enter

Type "n"

Sleep 350ms 
Enter

Sleep 2s
