Output manual-install.gif

Set Width 1200
Set Height 600
Set Theme "Dracula"
Set TypingSpeed 0.1
Set FontFamily "JetBrains Mono"

Set WindowBar Colorful
Set MarginSize 20
Set MarginFill "#bd93f9"


Set CornerRadius 10
Set Padding 20

Type@100ms "git clone https://github.com/pspiagicw/qemantra"

Sleep 350ms

Enter

Hide

Sleep 120s

Show

Type "cd qemantra"

Sleep 350ms

Enter

Sleep 2s

Type "make build"

Sleep 350ms

Enter

Sleep 12s

Type "./qemantra"

Enter

Sleep 2s
